set_property SRC_FILE_INFO {cfile:/home/nakashima/projects/zynq-7010/tutorial/ram/ram.srcs/constrs_1/new/ram.xdc rfile:../../../ram.srcs/constrs_1/new/ram.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U18 [get_ports {clk}]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N15 [get_ports {rst_n}]
