set_property SRC_FILE_INFO {cfile:/home/nakashima/projects/zynq-ax7010/tutorial/fifo/fifo.srcs/constrs_1/new/fifo.xdc rfile:../../../fifo.srcs/constrs_1/new/fifo.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U18 [get_ports {sys_clk}]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N15 [get_ports {rst_n}]
